### ISSUE TITLE
Minimum Viable Product

### ISSUE THREAD

**Issue by peschkaj** [TsebMagi/SealsOfFate#23]
- [ ] #3 Crate a room with a Player
- [ ] #4 Add enemies to rooms
- [ ] #5 Combat/AI
- [ ] #6 Create multiple rooms
- [ ] #9 Level Boss
